### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by patrick-kidger** [Roger-luo/FromFile.jl#1]
I've not run this yet, just comments from looking over it quickly:

---

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L27

Probably don't want to `gensym` on every invocation; we'd like to use the same `__toplevel__` every time. (And if we assume that nothing else is defining `__toplevel__` then we woudn't need a `gensym` at all.)

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L31

This should probably be subject to some more error checking to make sure the syntax matches exactly, rather than just tossing out all the symbols. (I realise that this is a first draft and you may already be thinking about this.)

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L57

I don't think it actually matters either way: an absolute path should be as good an identifier as the path relative to root. Is there a reason to prefer this here?

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L63

As per my comment I still think this should be a full module.

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L66

Isn't this just going to get evaluated the first time around, and then not every other time around? I.e. it can be folded into the if statement above, and `loaded_path` removed entirely?

https://github.com/Roger-luo/FromFile.jl/blob/d364660401f80ced70d6e247cd3be7c6901ee70a/src/FromFile.jl#L77

The implementation of this is wrong.

**Comment by Roger-luo** [comment]
> This should probably be subject to some more error checking to make sure the syntax matches exactly, rather than just tossing out all the symbols. (I realise that this is a first draft and you may already be thinking about this.)

I think the `using X` expression is parsed in this way, this check is not actually necessary, but more like a just in case thing.

> I don't think it actually matters either way: an absolute path should be as good an identifier as the path relative to root. Is there a reason to prefer this here?

`abspath` will break static compilation and make the package no longer relocatable. (as I mentioned on discourse)

> As per my comment I still think this should be a full module.

I think it's better to check what `Main` contains somewhere later, I think the only requirement here is to allow REPL code copy-pastable. 

> Isn't this just going to get evaluated the first time around, and then not every other time around? I.e. it can be folded into the if statement above, and loaded_path removed entirely?

yeah.

> The implementation of this is wrong.

well, it's a bit weird when you say it is wrong but don't say why :-) this gives me the right root module of `Main` and the package module, so I don't see why?

**Comment by Roger-luo** [comment]
OK I think the major difference is whether there is a default `eval` and `include`. I think the answer is yes, I'll use a normal module for the implicit file module then.

**Comment by Roger-luo** [comment]
> Probably don't want to gensym on every invocation; we'd like to use the same __toplevel__ every time. (And if we assume that nothing else is defining __toplevel__ then we woudn't need a gensym at all.)

**Comment by Roger-luo** [comment]
So this package will be used for some other purpose besides the draft:

1. as a compatible package when the developer wants to make things compatible with older versions of julia
2. as a package that allows people to try it out before it is built into Julia

A typical Julia syntax addition usually goes with implementing a macro in the external package first, then slowly gets into the compiler. Now to answer other questions

> Probably don't want to gensym on every invocation; we'd like to use the same __toplevel__ every time. (And if we assume that nothing else is defining __toplevel__ then we woudn't need a gensym at all.)

I don't see any way to guarantee someone defines the `__toplevel__`, so I'm not sure about this. A better way might be to mangling this symbol using `#` instead.

> checking to make sure the syntax matches exactly

This is not our job, but the parser's job. Besides, this won't actually be a `Symbol` by the implementation of the parser, I do it more for just in case, and more to make linters happy.

> As per my comment I still think this should be a full module.

I'm not sure, I feel we should disable `include` inside top-level scope for files, or should we? I think the major difference is whether there is a default `eval` and `include` or not.

> Isn't this just going to get evaluated the first time around, and then not every other time around? I.e. it can be folded into the if statement above, and loaded_path removed entirely?

right, done.

> The implementation of this is wrong.

would be nice and make things easier if you can tell why it's wrong. But yeah, I forget to store a previous module here.

**Comment by Roger-luo** [comment]
> I don't think it actually matters either way: an absolute path should be as good an identifier as the path relative to root. Is there a reason to prefer this here?

this will break static compilation if it's not a relative path. Maybe reading this would help https://julialang.github.io/PackageCompiler.jl/dev/devdocs/relocatable_part_3/

**Comment by patrick-kidger** [comment]
The changes look good.

> I'm not sure, I feel we should disable include inside top-level scope for files, or should we? I think the major difference is whether there is a default eval and include or not.

I think those should be available. Why do you suggest they shouldn't? (I notice that it is now `module` rather than `baremodule` so maybe I've convinced you?)

> this will break static compilation if it's not a relative path

Makes sense, thankyou.

> I don't see any way to guarantee someone defines the __toplevel__, so I'm not sure about this. A better way might be to mangling this symbol using # instead.

Does Julia have some special behaviour for `#` that I'm not aware of? (Not that I could find.) If not then this still has the same issue, just with a different name.

Ultimately I think we just have to insist that we be the ones to define `__toplevel__`, as we can't distinguish between one that we've put there and one that has been put there before.

https://github.com/Roger-luo/FromFile.jl/blob/b443a303ae0d5e0648cecf6b2d14c6e254d23dec/src/FromFile.jl#L5

I don't think this is used?

https://github.com/Roger-luo/FromFile.jl/blob/b443a303ae0d5e0648cecf6b2d14c6e254d23dec/src/FromFile.jl#L24

It would be good to factor out the `Symbol` creation to a variable that is reused. That serves as a "single source of truth", without relying on all three here doing the same thing.

https://github.com/Roger-luo/FromFile.jl/blob/b443a303ae0d5e0648cecf6b2d14c6e254d23dec/src/FromFile.jl#L66

The error message shouldn't assume that `$name` is a module.

In any case, is an error message really necessary here? This will eventually raise an error when the expression returned from the macro is evaluated. This then means the code here can be simplified: if the `name` argument isn't passed then `load_module` can be lifted out of the for loop it's called in.

**Comment by patrick-kidger** [comment]
In the interests of being helpful I've opened a PR for the above changes.

**Comment by Roger-luo** [comment]
OK closing this issue, let's move to the PR.
