### ISSUE TITLE
Multi-line imports

### ISSUE THREAD

**Issue by MilesCranmer** [Roger-luo/FromFile.jl#20]
What do you think about potentially adding a feature to allow multi-line imports, maybe like this?
```julia
@from "MyImport.jl" begin
    import one, two, three
    import four, five, six
    import seven, eight, nine
end
```

Right now for importing many objects, one either does [this](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/649e8457ae42fd7db979f10d214b6b4f9500966f/src/Core.jl#L7) or multiple `@from ... import` calls. 

Cheers

**Comment by patrick-kidger** [comment]
I'd be in favour, if you want to offer a PR on it. It should be pretty straightforward, just entailing an extra branch here:

https://github.com/Roger-luo/FromFile.jl/blob/ba3d96b57585a5710579d3d1f18729f06f5087e5/src/FromFile.jl#L41

to distinguish+process the proposed syntax.
