### ISSUE TITLE
@from "file.jl" (without import)

### ISSUE THREAD

**Issue by fonsp** [Roger-luo/FromFile.jl#24]
Sometimes you want to load a file without importing anything from it. For example, a file that sets up a global logger.

I want to propose the syntax:
```
@from "file.jl"
```
to import the file.jl. But unlike `inlcude("file.jl")`,
- The contents of `file.jl` are not inserted into the caller scope.
- The import is deduplicated
- It looks just like my other `@from` imports.

(This is the analogue of `import "./file.js"` in ES6 [[example](https://github.com/fonsp/Pluto.jl/blob/6a93017c541d32f2dce6893afd960c961a3d1cf3/frontend/common/PlutoConnection.js#L1-L3)])

This will be easy to implement after #22

**Comment by patrick-kidger** [comment]
So whilst I don't really see the harm in allowing the syntax for those who want it, I would note that the proposed use case is exactly the kind of thing we created FromFile to avoid.

The point of FromFile (or one of the points) is to better structure dependencies between files: no spooky action at a distance. Meanwhile having something happen as a result of an import is spooky.

**Comment by fonsp** [comment]
Valid point! For context, the reasons I am thinking of to load a file (once!) without importing is to set up integrations with another package, e.g. a file with Requires.jl statements, or defining a PlotRecipes recipe.

**Comment by fonsp** [comment]
Another use case is my `runtests.jl` file:
```julia
@from "test_this.jl"
@from "test_that.jl"
...
```

(I am a big fan of FromFile.jl and I want to use it for everything!) We are also currently discussing workflows in Pluto where you combine multiple notebooks into one, and this came up again.

Would a PR be welcome? I would be happy to implement it myself with tests!

**Comment by patrick-kidger** [comment]
Sure thing! We'd be happy to accept a PR on this.

**Comment by fonsp** [comment]
#33
