### ISSUE TITLE
Relative paths not resolved

### ISSUE THREAD

**Issue by MariusDrulea** [Roger-luo/FromFile.jl#27]
I have modified the chain and subchain example to illustrate the problem, see the attached archive for code.

Depending on how I include the ss1 module I get the following full names for ss1.Hello.

**Option1:** @from "subchain/subfolder/subchain1.jl" import ss1
**Option1 results is**: Main.D:\Software\repos\FromFile.jl-master\test\subchain\subfolder\../subsubchain1.jl.ss1.Hello

**Option2**: @from "subchain/subsubchain1.jl" import ss1
**Option2 result is**: ss1.Hello is: Main.D:\Software\repos\FromFile.jl-master\test\subchain/subsubchain1.jl.ss1.Hello

**Problem**: With Option1, the ".." in the path is not resolved. Although I am using the same Hello struct, I do get different full names for it. The result is that ss1 module is evaluated twice. 

Possible solution:
```
    if !isabspath(path) && basepath != ""
        path = joinpath(basepath, path) 
	path = abspath(path) ################# here is the extra line, shall we always solve relative paths?
    else
        path = abspath(path)
    end 
```

[subchain.zip](https://github.com/Roger-luo/FromFile.jl/files/6967605/subchain.zip)

**Comment by patrick-kidger** [comment]
Hmm. Okay, so I think this is an error happening specifically when:
- Having a module specified in a file
- such that that module has a `@from` statement inside it
- such that that `@from` statement uses a relative path
- and such that the module is `include`d into the REPL (i.e. is not part of a package)

And in this case, the deduplication doesn't trigger.

Does that sound correct?

I've opened #28 as a potential fix.

**Comment by MariusDrulea** [comment]
@patrick-kidger indeed, I don't have a package. #28 fixes the issue. Thanks.
