### ISSUE TITLE
discussion: @from as part of Julia, vscode julia intellisense for @from

### ISSUE THREAD

**Issue by MariusDrulea** [Roger-luo/FromFile.jl#34]
Hi,
I have implemented intellisense (auto-complete, click on symbols) for @from here: https://github.com/julia-vscode/StaticLint.jl/pull/319. VisualStudioCode julia extension can how handle the symbols included via @from and this is really working nice in my projects. In the PR however, the guys are not happy to accept a custom package in their instellisense. They are suggesting that FromFile shall merge into Julia first. Any thoughts?

**Comment by Roger-luo** [comment]
Well we have a proposal and there are quite a few people not like this idea. You could read the long discussion in JuliaLang/julia#4600 as mentioned in README. So I don't think this is gonna be in Julia base anytime soon unless it's widely used in the ecosystem which might force people who dislike it to reconsider the benefit.

**Comment by Roger-luo** [comment]
I'm wondering if StaticLint can provide a plug-in system to allow package authors to support custom lint tho like some of the python linter. From a first glance it doesn't look like having such mechanism.

**Comment by patrick-kidger** [comment]
Yeah, we'd love for this to become a built-in part of Julia! Not up to us, unfortunately.
