### ISSUE TITLE
Hiding paths in @from invocations

### ISSUE THREAD

**Issue by danielsoutar** [Roger-luo/FromFile.jl#38]
Hi there, really happy to be using this library and thanks for making it.

I had a question about having a slightly cleaner call to `@from`. While I like the current syntax, it would be nice if something like the following were possible:

```julia
# FromFileUtils.jl
module FromFileUtils

export path_to

const PROJECT_BASE = joinpath(splitpath(Base.current_project())[begin:end-1]...)
const SRC_BASE = joinpath(splitpath(PROJECT_BASE)..., "src")

path_dictionary = Dict{Symbol, String}(
    :LocalModuleC => joinpath(SRC_BASE, "LocalModuleC.jl")
)

function path_to(module_sym)
    if haskey(path_dictionary, module_sym)
        return path_dictionary[module_sym]
    end
    throw(ArgumentError("The requested module is not available."))
end

end  # module FromFileUtils

# some-file.jl
import ModuleA
import ModuleB

import FromFile: @from
@from "/path/to/FromFileUtils.jl" import FromFileUtils: path_to
@from path_to(:LocalModuleC) import LocalModuleC
```

There are several benefits of this approach:
* With the exception of `FromFileUtils.jl`, all other paths are hidden away from their respective users. Changing paths to files then only requires a change in a single file.
* It avoids the issue of relative imports altogether, since all paths used are absolute paths.
* It can be shorter in most cases, especially in tests.

I'm not necessarily asking for this to be supported as a feature of the library, but when I try the above, I get this error:

```julia
julia> @from path_to(:LocalModuleC) import LocalModuleC
ERROR: LoadError: MethodError: no method matching var"@from"(::LineNumberNode, ::Module, ::Expr, ::Expr)
Closest candidates are:
  var"@from"(::LineNumberNode, ::Module, ::String, ::Expr) at /path/to/FromFile/94kjn/src/FromFile.jl:15
  var"@from"(::LineNumberNode, ::Module, ::String) at /path/to/FromFile/94kjn/src/FromFile.jl:19
in expression starting at REPL[16]:1
```

I suspect that by virtue of being a macro that a function call cannot be supported without a change to `FromFile` itself. A macro might work, but I am not sure of how this would look.

Any advice or suggestions very welcome. Thanks for your time reading this.

**Comment by patrick-kidger** [comment]
So I think something like this probably out of scope for FromFile.jl. What you're describing is, I think, quite an opionated way of accessing files (even more so than FromFile already is!) as it requires maintaining a registry of symbol-file lookups.

But if you want to build something like this yourself on top of FromFile, that is totally possible. The following will work:

```julia
@eval @from $(path_to(:LocalModuleC)) import foo
```

which you can of course wrap up into your own macro if you want to keep things tidier.

**Comment by danielsoutar** [comment]
Totally agree - thanks very much for the quick reply and your suggestion!
