### ISSUE TITLE
Clarify that path seperators are automatically translated in README.

### ISSUE THREAD

**Issue by JacobMacWilliams** [Roger-luo/FromFile.jl#45]
I understand that the path separator used to formulate the path is irrelevant and autotranslated following the following call in from_local_file:
```
    if !isabspath(path) && basepath != ""
        path = joinpath(basepath, path)
    end
    path = abspath(path)
```
While this behavior is fairly common sense, I think it could be clarified in the documentation. As a noobie to Julia I spent a significant amount of time thinking that this was not the case and trying to find some kind of work around.

**Comment by Roger-luo** [comment]
Sure, please feel free to edit the README and submit a PR!

**Comment by JacobMacWilliams** [comment]
Will do
